### install

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
!pip install JPype1
!pip install konlpy

Collecting JPype1
  Downloading JPype1-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (448 kB)
     |████████████████████████████████| 448 kB 5.1 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1) (3.10.0.2)
Installing collected packages: JPype1
Successfully installed JPype1-1.3.0
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 1.2 MB/s
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.19.5)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.3.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (3.10.0.2)
Installing collected packages: konlpy
Successfully installed konlpy-0.6.0

In [ ]:
import pandas as pd

# 형태소분석
from konlpy.tag import Okt

# 갯수카운트
from collections import Counter

### 엑셀에서 df가져오기

In [ ]:
##### 쇼핑에서 가져올 때 #####

file = ['네이버쇼핑_IT.xlsx','네이버쇼핑_경제.xlsx',
        '네이버쇼핑_여행.xlsx','네이버쇼핑_취미.xlsx']
dfname=['it','경제','여행','취미']

for name,i in zip(file,dfname):
    df_sh = pd.read_excel(f'/content/drive/My Drive/Colab Notebooks/{name}',
                          engine='openpyxl', header = None, names=['도서명','분류1','분류2'])
    globals()['df_sh_{}'.format(i)]=df_sh

df_sh_it

                                          도서명        분류1        분류2
0                   한정희 된다 7일 실무 엑셀 [이지스퍼블리싱]    오피스활용도서   MS Excel
1               파이썬 머신러닝 완벽 가이드 / 위키북스 (책,도서)   프로그래밍 언어        NaN
2                윤성우의 열혈 c 프로그래밍 책 윤성우 오렌지미디어   프로그래밍 언어        NaN
3                       영상 편집을 위한 프리미어 프로 제이펍  그래픽/멀티미디어  그래픽일반/자료집
4                  do it 점프 투 파이썬 / 이지스퍼블리싱 책   프로그래밍 언어        NaN
..                                        ...        ...        ...
495              autocad 2010 쉽게 배우기 책 (영진닷컴)  그래픽/멀티미디어   그래픽툴/저작툴
496                            자바스크립트 패턴과 테스트   프로그래밍 언어        NaN
497           이상만 (메카피아) 솔리드웍스 정적구조 공학해석 실무 책  그래픽/멀티미디어   그래픽툴/저작툴
498  sql server로 배우는 데이터베이스 개론과 실습 책 (한빛아카데미)  OS/데이터베이스        NaN
499            [보리보리/유니오니아시아]초보자를 위한 c++ 200제   프로그래밍 언어        NaN

[500 rows x 3 columns]

In [ ]:
df_sh_경제

                                                   도서명      분류1     분류2
0              민음인 부자 아빠 가난한 아빠. 1(20주년 특별 기념판)(개정증보판)   재테크/투자   재테크일반
1                                   거인의 포트폴리오 / 페이지2북스   재테크/투자   주식/증권
2    한경무크 광장 변호사들이 알려주는 궁금한 중대재해처벌법 / 한국경제신문 / 한국경제매거진       경영    경영실무
3                                        개미 5년, 세후 55억   재테크/투자   주식/증권
4                                 이선미 싱글맘 부동산 경매로 홀로서기   재테크/투자  부동산/경매
..                                                 ...      ...     ...
495                 (한스미디어) 주식 투자 잘하는 사람들의 7가지 무기 책 김진   재테크/투자   주식/증권
496                          곽상빈 [평단] 주린이를 위한 친절한 주식공부   재테크/투자   주식/증권
497                   교통사고 피해보상 아는 만큼 더 받는다 / 크라운출판사 책   재테크/투자   재테크일반
498                                [유니오니아시아] 한마디면 충분하다  마케팅/세일즈  영업/세일즈
499                                [밀크북]워렌 버핏의 가치투자 전략   재테크/투자   주식/증권

[500 rows x 3 columns]

In [ ]:
df_sh_여행

                                                   도서명   분류1         분류2
0                              식객 허영만의 백반기행 세트(1-2권) 책  테마여행        맛집여행
1                        식객 허영만의 백반기행 1 2 허영만 책 도서 가디언  테마여행        맛집여행
2                                 [가디언] 식객 허영만의 백반기행 2  테마여행        맛집여행
3                                     우리는 어쩌다 런던에서 서유진  국내여행         제주도
4    [가디언] 식객 허영만의 백반기행 세트(1-2권) 식객이 뽑은 진짜 맛집 97911...  테마여행        맛집여행
..                                                 ...   ...         ...
495                                      영국 장식 미술 기행 책  해외여행        유럽여행
496                               (황금비율) 아이슬란드 여행 지도 책  해외여행        유럽여행
497                     뉴노멀, 한 달 살기 동유럽 / 나우출판사 (책,도서)  해외여행        유럽여행
498                                     유적지에서 만나는 화랑정신  테마여행     역사/문학기행
499                               [유니오니아시아] 남미 열정의 라세티  해외여행  미국/캐나다/중남미

[500 rows x 3 columns]

In [ ]:
df_sh_취미

                                             도서명    분류1         분류2
0                          소워니놀이터의 띠부띠부 직업놀이 시대인  취미/레저        취미기타
1    소워니놀이터의 띠부띠부 가게놀이 -떼었다 붙였다 하면서 즐기는 종이놀이 도안집  취미/레저        취미기타
2                            2022 이철수 판화 달력(탁상용)  취미/레저        취미기타
3                 글씨교정선틀에서 악필을 바로잡는 악필교정의 정석1 기본  취미/레저        취미기타
4                   (삼원북스) 2022 나합격 식품기사 필기 + 부록     건강  의학/식품/생활과학
..                                           ...    ...         ...
495    로제의 모티브 손뜨개 소품(모티브 하나하나로 이어가는 따뜻한 감성 손뜨개)  취미/레저  뜨개질/퀼트/십자수
496                         (윌북) 면역의 힘 책 제나 마치오키     건강    건강정보/이야기
497                       [활동카드동물걸음 각종목별 12가지운동]     건강     건강운동 기타
498         (나비의활주로) 인스타그램 마케팅 잘하는 사람은 이렇게 합니다 책  취미/레저        취미기타
499                                      손바느질 소품  취미/레저        취미기타

[500 rows x 3 columns]

In [ ]:
kbb_list = ['교보문고_종합 베스트_연간_2018년_경제경영202201171730.xlsx',
        '교보문고_종합 베스트_연간_2018년_기술_컴퓨터202201171729.xlsx',
        '교보문고_종합 베스트_연간_2018년_여행202201171730.xlsx',
        '교보문고_종합 베스트_연간_2018년_취미_스포츠202201171733.xlsx',
        '교보문고_종합 베스트_연간_2018년_분야_종합202201191022.xlsx'
        '교보문고_종합 베스트_연간_2019년_경제경영202201171730.xlsx',
        '교보문고_종합 베스트_연간_2019년_기술_컴퓨터202201171729.xlsx',
        '교보문고_종합 베스트_연간_2019년_여행202201171730.xlsx',
        '교보문고_종합 베스트_연간_2019년_취미_스포츠202201171732.xlsx',
        '교보문고_종합 베스트_연간_2019년_분야_종합202201191022.xlsx',
        '교보문고_종합 베스트_연간_2020년_경제경영202201171730.xlsx',
        '교보문고_종합 베스트_연간_2020년_기술_컴퓨터202201171730.xlsx',
        '교보문고_종합 베스트_연간_2020년_여행202201171729.xlsx',
        '교보문고_종합 베스트_연간_2020년_취미_스포츠202201171730.xlsx',
        '교보문고_종합 베스트_연간_2020년_분야_종합202201191022.xlsx',
        '교보문고_종합 베스트_연간_2021년_경제경영202201171729.xlsx',
        '교보문고_종합 베스트_연간_2021년_기술_컴퓨터202201171730.xlsx',
        '교보문고_종합 베스트_연간_2021년_여행202201171729.xlsx',
        '교보문고_종합 베스트_연간_2021년_취미_스포츠202201171727.xlsx',
        '교보문고_종합 베스트_연간_2021년_분야_종합202201171707.xlsx']

# kbb_list에서 df파일명 만듦
dfname2=[]
for i in range(len(kbb_list)):
    dfname2.append(kbb_list[i].replace('교보문고_종합 베스트_연간_','').split('2022')[0])


for name,i in zip(kbb_list,dfname2):
    df_best = pd.read_excel(f'/content/drive/My Drive/Colab Notebooks/{name}', engine='openpyxl',header=1)
    df_best.drop([0], inplace = True)
    globals()['df_best{}_'.format(i)]=df_best

df_best_2018년_분야_종합

      순위          ISBN  ...     분야       정가
1      1  9.788926e+12  ...  시/에세이  12000.0
2      2  9.791162e+12  ...  시/에세이  13800.0
3      3  9.788957e+12  ...  시/에세이  13800.0
4      4  9.788937e+12  ...     소설  13000.0
5      5  9.791187e+12  ...  시/에세이  13800.0
..   ...           ...  ...    ...      ...
196  196  9.788984e+12  ...     소설  13000.0
197  197  9.788959e+12  ...  시/에세이  12800.0
198  198  9.788955e+12  ...     소설  13500.0
199  199  9.788965e+12  ...    외국어  19800.0
200  200  9.791187e+12  ...  경제/경영  20000.0

[200 rows x 8 columns]

In [ ]:
df_best_2019년_분야_종합

      순위          ISBN  ...     분야       정가
1      1  9.788955e+12  ...  시/에세이  13500.0
2      2  9.791187e+12  ...  시/에세이  15000.0
3      3  9.791187e+12  ...  시/에세이  13800.0
4      4  9.791188e+12  ...  경제/경영  14000.0
5      5  9.791131e+12  ...     인문  16000.0
..   ...           ...  ...    ...      ...
196  196  9.788991e+12  ...     소설  16800.0
197  197  9.788936e+12  ...     소설  12000.0
198  198  9.791157e+12  ...  경제/경영  18000.0
199  199  9.791162e+12  ...  시/에세이  14000.0
200  200  9.791158e+12  ...  경제/경영  35000.0

[200 rows x 8 columns]

In [ ]:
df_best_2020년_분야_종합

      순위          ISBN  ...     분야       정가
1      1  9.791190e+12  ...   자기계발  16000.0
2      2  9.791188e+12  ...  경제/경영  16800.0
3      3  9.788936e+12  ...     소설  12000.0
4      4  9.788948e+12  ...   자기계발  16000.0
5      5  9.791190e+12  ...     인문  19800.0
..   ...           ...  ...    ...      ...
196  196  9.788998e+12  ...     소설  13000.0
197  197  9.791136e+12  ...     만화   5000.0
198  198  9.791188e+12  ...   자기계발  16500.0
199  199  9.791197e+12  ...  시/에세이  15000.0
200  200  9.791165e+12  ...  경제/경영  18000.0

[200 rows x 8 columns]

In [ ]:
df_best_2021년_분야_종합

      순위          ISBN  ...       분야       정가
1      1  9.791165e+12  ...       소설  13800.0
2      2  9.791160e+12  ...    경제/경영  18000.0
3      3  9.791191e+12  ...       소설  15800.0
4      4  9.788936e+12  ...    정치/사회  17000.0
5      5  9.791190e+12  ...       인문  18000.0
..   ...           ...  ...      ...      ...
196  196  9.791159e+12  ...  어린이(초등)  12000.0
197  197  9.788949e+12  ...  어린이(초등)  11000.0
198  198  9.788993e+12  ...    정치/사회  17000.0
199  199  9.788917e+12  ...      외국어  12900.0
200  200  9.791187e+12  ...       인문  14000.0

[200 rows x 8 columns]